name: "PHP Linter"

on:
  pull_request:
    paths:
      - "**.php"
      - ".github/linters/phpcs.xml"
      - ".github/workflows/php-lint.yml"

jobs:
  phpcs:
    name: "PHP Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: "/php/**/*.php"

      - name: Install PHP_CodeSniffer
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - uses: thenabeel/action-phpcs@v8
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          files: "**.php"
          phpcs_path: php phpcs.phar
          standard: ".github/linters/phpcs.xml"
